name: Frontend Deployment

on:
  workflow_dispatch:

permissions: 
  contents: read  # pipeline needs perission to read our repository files // Pipeline allowed to read our repository files.
  pages: write    # to deploy our website to github page, without this deployment fail
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       # Build has 3 steps
      - name: Get code
        uses: actions/checkout@v4

      - name: Check files
        run: |
          ls
          echo "Frontend files found"

      - name: Upload website   # Prepares our website files so that github pages can deploy them.
        uses: actions/upload-pages-artifact@v3  #Files r uploaded as pages artifact
        with:  
          path: .   #Upload the file from this directory here, . means current directory. Telling it to upload everything in the current directory

  deploy:   #First job prepared the website and the 2nd job actually deploys
    needs: build
    runs-on: ubuntu-latest  #GitHub gives the deploy job an Ubuntu runner. GitHub gives the deploy job another temporary Ubuntu machine

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} #This is used to show the actual GitHub Pages URL after deployment.

    steps:
      - name: Deploy to GitHub Pages
        id: deployment   #Get the page_url output from the step whose ID is deployment. So, this and url are connected.
        uses: actions/deploy-pages@v4 #This is the step that actually publishes your website.
